### ISSUE TITLE
[BUG] Negative expiration and due dates when running WHMCS native domain sync

### ISSUE THREAD

**Issue by mitch2k** [openprovider/Openprovider-WHMCS-domains#86] opened 2020-05-22 11:14 UTC
Hi,

there seems to (still) be an issue that some domains get a wrong date synced, when using the WHMCS domain sync.

In the log:

> - bouxxxx.be: Expiry Date updated to 28/04/2021, Next Due Date updated to 28/04/2021
> - eshuttxxxx.be: Expiry Date updated to 02/05/2021, Next Due Date updated to 02/05/2021
> - buggyfunxxxx.com: Expiry Date updated to 30/11/-0001, Next Due Date **updated to 30/11/-0001**
> - e-shuttlxxxx.be: Expiry Date updated to 30/11/-0001, Next Due Date **updated to 30/11/-0001**
> - huisvaxxxx.be: Expiry Date updated to 18/05/2021, Next Due Date updated to 18/05/2021

In the DB:
![image](https://user-images.githubusercontent.com/22825975/82661939-4bf48980-9c2d-11ea-9b69-cc8ffe22b459.png)

**Comment by mitch2k** [comment] 2020-05-22 11:42
When turning the OP own sync back on, this seems to be rectified:

![image](https://user-images.githubusercontent.com/22825975/82664500-21f19600-9c32-11ea-8b99-8104726113a8.png)

**Comment by sapillai** [comment] 2024-06-20 06:48
Hi @mitch2k,

I am closing this issue as I am unable to reproduce the problem with recent versions of the module.
 
Please try the WHMCS native sync with the latest version of the [module](https://github.com/openprovider/Openprovider-WHMCS-domains/archive/refs/tags/v5.8.0.zip). If you experience any problems, please contact our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) with following details so that we can investigate it:

- Reseller ID
- [module logs](https://docs.whmcs.com/Troubleshooting_Module_Problems)
- WHMCS, Openprovider module and PHP version details.

**Closed by sapillai** 2024-06-20 06:48 UTC
Labels: bug
