### ISSUE TITLE
[BUG] Another premium domain price lookup error

### ISSUE THREAD

**Issue by willdashwood** [openprovider/Openprovider-WHMCS-domains#231] opened 2022-04-25 08:55 UTC
Customer has just placed an order with us for db.group. This is a premium domain; £2,497.50, ouch!

<img width="529" alt="Screenshot 2022-04-25 at 09 38 13" src="https://user-images.githubusercontent.com/4964200/165052711-bd7fdd0c-3198-467f-89a4-ff4159a96e43.png">

But WHMCS has only charged our customer the standard base price of a .group domain.

<img width="942" alt="Screenshot 2022-04-25 at 09 42 43" src="https://user-images.githubusercontent.com/4964200/165053270-7cd51910-02eb-435a-bb46-d4aefed2955d.png">

I've checked my config and premium domains are definitely enabled both in WHMCS and advanced-module-configurations.php

`'OpenproviderPremium'               => true,`

<img width="365" alt="Screenshot 2022-04-25 at 09 45 50" src="https://user-images.githubusercontent.com/4964200/165053829-82d6841e-785b-4507-b985-615f9ba9f037.png">

The strange thing is, when I go to place a test order for this domain now, it does give the right price.

<img width="464" alt="Screenshot 2022-04-25 at 09 44 41" src="https://user-images.githubusercontent.com/4964200/165055243-72489fbf-2ed6-4b99-946d-faa69ffce6b6.png">

So I'm wondering, is this a module issue or a API lookup issue? It wouldn't be the first time we've had the API report the wrong price and then magically correct itself later. To be honest, with all the hassle we get from premium domains, we're thinking of just discontinuing them.

**Comment by wmetge** [comment] 2022-04-27 07:45
Hello @willdashwood thanks for bringing this to our attention. 

My colleague has looked at the API logs, and it seems that all responses to your module's queries for db.group correctly indicated that the domain was premium and included the price. For now I  looks like in this case the source of the issue is not the API. 

I've noted the issue for our developer to investigate, but it's a difficult issue to solve without being able to to reproduce.

Please do let us know if you are able to identify any factors which might lead to this situation.

**Comment by willdashwood** [comment] 2022-04-27 07:50
Hi @wmetge, glad to see you're still around. I'm afraid I don't have any further information to debug this. Perhaps there could be an option added to the module to log API calls and response so we can debug what's going on?

If I disable premium domains will that simply prevent someone from purchasing them from us?

**Comment by wmetge** [comment] 2022-04-27 08:01
@willdashwood, sorry the answers are few and far between, but trying to help out where I can. 

 Regarding the module logging, this can be turned on in the WHMCS admin area:  Configuration > System Logs > Module Log. I understand that this logging takes up a noticeable amount of space when being run on a production machine.  

> If I disable premium domains will that simply prevent someone from purchasing them from us?
My understanding of the WHMCS logic when premium domains are disabled is that premium domains will be indicated as 'not free to register' if the end user searches for one.

**Comment by wmetge** [comment] 2022-04-27 08:14
>Module logging does indeed incur a performance penalty but if we were to do that, would the API calls be logged? 

Yes, it should include the parameters of the call, and the raw API response

**Comment by sapillai** [comment] 2024-06-03 13:42
Hi @willdashwood,

I am closing this one for now as we don't have enough information, logs to reproduce the issue and to investigate it. Premium domain price check is working correctly in the [latest version of the module](https://github.com/openprovider/Openprovider-WHMCS-domains/releases/tag/v5.8.0). 

If you notice any such issues, please contact our [support team](https://support.openprovider.eu/hc/en-us/articles/360001674667-Contact-Openprovider-Support) with following details so that we can investigate it:

- [module logs](https://docs.whmcs.com/Troubleshooting_Module_Problems). You can disable module logging after reproducing and collecting logs. 
- WHMCS, Openprovider module and PHP version details.

**Closed by sapillai** 2024-06-03 13:42 UTC
Labels: bug
